---
- name: Change permission of the key
  hosts: localhost
  become: no
  tasks:
  - name: change permissoin of the generated key
    file:
      path: "./myways.pem"
      owner: "{{ lookup('env', 'USER') }}"
      mode: 0400

- name: Create backend configuration
  hosts: tag_Name_webos
  vars_files:
  - var.yml
  tasks:
  - name: check if httpd and python packages are present or not
    yum:
      name: 
        - httpd
        - python3
      state: present
  
  - name: Start httpd services
    service:
      name: httpd
      enabled: yes
      state: started

  - name: copy frontend code
    copy:
      src: html
      dest: /var/www/
      setype: httpd_sys_content_t

  - name: copy backend create code
    template:
      src: create.py
      dest: '/var/www/cgi-bin/'
      setype: httpd_sys_content_t

  - name: copy backend search code
    template:
      src: search.py
      dest: '/var/www/cgi-bin/'

  - name: copy backend delete code
    template:
      src: delete.py
      dest: '/var/www/cgi-bin'
